/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/items/': RouteRecordInfo<
      '/items/',
      '/items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/items/[id]': RouteRecordInfo<
      '/items/[id]',
      '/items/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/items/filter': RouteRecordInfo<
      '/items/filter',
      '/items/filter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/items/modify/[[id]]': RouteRecordInfo<
      '/items/modify/[[id]]',
      '/items/modify/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | '/profile/import-items'
      | '/profile/options/core'
      | '/profile/options/locale'
      | '/profile/update-password'
    >,
    '/profile/import-items': RouteRecordInfo<
      '/profile/import-items',
      '/profile/import-items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/options/core': RouteRecordInfo<
      '/profile/options/core',
      '/profile/options/core',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/options/locale': RouteRecordInfo<
      '/profile/options/locale',
      '/profile/options/locale',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/update-password': RouteRecordInfo<
      '/profile/update-password',
      '/profile/update-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/redirect': RouteRecordInfo<
      '/redirect',
      '/redirect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | '/reset-password/new-password'
    >,
    '/reset-password/new-password': RouteRecordInfo<
      '/reset-password/new-password',
      '/reset-password/new-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signin': RouteRecordInfo<
      '/signin',
      '/signin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signup': RouteRecordInfo<
      '/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/items/index.vue': {
      routes:
        | '/items/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/items/[id].vue': {
      routes:
        | '/items/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/items/filter.vue': {
      routes:
        | '/items/filter'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/items/modify/[[id]].vue': {
      routes:
        | '/items/modify/[[id]]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
        | '/profile/import-items'
        | '/profile/options/core'
        | '/profile/options/locale'
        | '/profile/update-password'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/profile/import-items.vue': {
      routes:
        | '/profile/import-items'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile/options/core.vue': {
      routes:
        | '/profile/options/core'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile/options/locale.vue': {
      routes:
        | '/profile/options/locale'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/profile/update-password.vue': {
      routes:
        | '/profile/update-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/redirect.vue': {
      routes:
        | '/redirect'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
        | '/reset-password/new-password'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/reset-password/new-password.vue': {
      routes:
        | '/reset-password/new-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/signin.vue': {
      routes:
        | '/signin'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/signup.vue': {
      routes:
        | '/signup'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
