import type { laundryIcon } from '@/interfaces/laundryIcon'

export const laundryIcons: Array<laundryIcon> = [
  {
    _id: 'wash',
    icon: 'app:laundry-icon-wash',
    path: '/icons/laundry/washing/wash.svg',
    group: 'washing',
    description: 'Wash',
  },
  {
    _id: 'do-not-wash',
    icon: 'app:laundry-icon-do-not-wash',
    path: '/icons/laundry/washing/do-not-wash.svg',
    group: 'washing',
    description: 'Do not wash',
  },
  {
    _id: 'wash-hand',
    icon: 'app:laundry-icon-wash-hand',
    path: '/icons/laundry/washing/hand-wash.svg',
    group: 'washing',
    description: 'Hand wash',
  },
  {
    _id: 'wash-30',
    icon: 'app:laundry-icon-wash-30',
    path: '/icons/laundry/washing/wash-at-or-below-30.svg',
    group: 'washing',
    description: 'Wash at 30 or lower °C',
  },
  {
    _id: 'wash-40',
    icon: 'app:laundry-icon-wash-40',
    path: '/icons/laundry/washing/wash-at-or-below-40.svg',
    group: 'washing',
    description: 'Wash at 40 or lower °C',
  },
  {
    _id: 'wash-50',
    icon: 'app:laundry-icon-wash-50',
    path: '/icons/laundry/washing/wash-at-or-below-50.svg',
    group: 'washing',
    description: 'Wash at 50 or lower °C',
  },
  {
    _id: 'wash-60',
    icon: 'app:laundry-icon-wash-60',
    path: '/icons/laundry/washing/wash-at-or-below-60.svg',
    group: 'washing',
    description: 'Wash at 60 or lower °C',
  },
  {
    _id: 'iron',
    icon: 'app:laundry-icon-iron',
    path: '/icons/laundry/ironing/iron.svg',
    group: 'ironing',
    description: 'Iron',
  },
  {
    _id: 'do-not-iron',
    icon: 'app:laundry-icon-do-not-iron',
    path: '/icons/laundry/ironing/do-not-iron.svg',
    group: 'ironing',
    description: 'Do not iron',
  },
  {
    _id: 'iron-low-temperature',
    icon: 'app:laundry-icon-iron-low-temperature',
    path: '/icons/laundry/ironing/iron-low-temperature.svg',
    group: 'ironing',
    description: 'Iron low temp. (max 110 °C)',
  },
  {
    _id: 'iron-medium-temperature',
    icon: 'app:laundry-icon-iron-medium-temperature',
    path: '/icons/laundry/ironing/iron-medium-temperature.svg',
    group: 'ironing',
    description: 'Iron medium temp. (max 150 °C)',
  },
  {
    _id: 'iron-high-temperature',
    icon: 'app:laundry-icon-iron-high-temperature',
    path: '/icons/laundry/ironing/iron-high-temperature.svg',
    group: 'ironing',
    description: 'Iron high tempe. (max 200 °C)',
  },
  {
    _id: 'bleach',
    icon: 'app:laundry-icon-bleach',
    path: '/icons/laundry/bleaching/bleach.svg',
    group: 'bleaching',
    description: 'Bleach',
  },
  {
    _id: 'do-not-bleach',
    icon: 'app:laundry-icon-do-not-bleach',
    path: '/icons/laundry/bleaching/do-not-bleach.svg',
    group: 'bleaching',
    description: 'Do not bleach',
  },
  {
    _id: 'bleach-with-chlorine',
    icon: 'app:laundry-icon-bleach-with-chlorine',
    path: '/icons/laundry/bleaching/bleach-with-chlorine.svg',
    group: 'bleaching',
    description: 'Bleach with chlorine',
  },
  {
    _id: 'bleach-only-non-chlorine',
    icon: 'app:laundry-icon-bleach-non-chlorine',
    path: '/icons/laundry/bleaching/bleach-non-chlorine.svg',
    group: 'bleaching',
    description: 'Bleach only non chlorine',
  },
  {
    _id: 'dry-tumble',
    icon: 'app:laundry-icon-dry-tumble',
    path: '/icons/laundry/drying/dry-tumble.svg',
    group: 'drying',
    description: 'Tumble dry',
  },
  {
    _id: 'do-not-tumble-dry',
    icon: 'app:laundry-icon-do-not-tumble-dry',
    path: '/icons/laundry/drying/do-not-dry-tumble.svg',
    group: 'drying',
    description: 'Do not tumble dry',
  },
  {
    _id: 'dry-tumble-low-heat',
    icon: 'app:laundry-icon-dry-tumble-low-heat',
    path: '/icons/laundry/drying/dry-tumble-low-heat.svg',
    group: 'drying',
    description: 'Tumble dry on low heat',
  },
  {
    _id: 'dry-tumble-medium-heat',
    icon: 'app:laundry-icon-dry-tumble-medium-heat',
    path: '/icons/laundry/drying/dry-tumble-medium-heat.svg',
    group: 'drying',
    description: 'Tumble dry on medium heat',
  },
  {
    _id: 'dry-drip',
    icon: 'app:laundry-icon-dry-drip',
    path: '/icons/laundry/drying/dry-drip.svg',
    group: 'drying',
    description: 'Drip dry',
  },
  {
    _id: 'dry-flat',
    icon: 'app:laundry-icon-dry-flat',
    path: '/icons/laundry/drying/dry-flat.svg',
    group: 'drying',
    description: 'Dry flat',
  },
  {
    _id: 'dry-clean',
    icon: 'app:laundry-icon-dry-clean',
    path: '/icons/laundry/dry-cleaning/dry-clean.svg',
    group: 'dry cleaning',
    description: 'Dry clean',
  },
  {
    _id: 'do-not-dry-clean',
    icon: 'app:laundry-icon-do-not-dry-clean',
    path: '/icons/laundry/dry-cleaning/do-not-dry-clean.svg',
    group: 'dry cleaning',
    description: 'Do not dry clean',
  },
  {
    _id: 'dry-clean-hydrocarbon-solvent-only',
    icon: 'app:laundry-icon-dry-clean-hydrocarbon-solvent-only',
    path: '/icons/laundry/dry-cleaning/dry-clean-hydrocarbon-solvent-only.svg',
    group: 'dry cleaning',
    description: 'Dry clean with hydrocarbon solvent only',
  },
  {
    _id: 'dry-clean-gentle-hydrocarbon-solvent-only',
    icon: 'app:laundry-icon-dry-clean-gentle-hydrocarbon-solvent-only',
    path: '/icons/laundry/dry-cleaning/dry-clean-gentle-hydrocarbon-solvent-only.svg',
    group: 'dry cleaning',
    description: 'Gentle clean with hydrocarbon solvent only',
  },
  {
    _id: 'dry-clean-very-gentle-with-hydrocarbon-solvents',
    icon: 'app:laundry-icon-dry-clean-very-gentle-hydrocarbon-solvent-only',
    path: '/icons/laundry/dry-cleaning/dry-clean-very-gentle-hydrocarbon-solvent-only.svg',
    group: 'dry cleaning',
    description: 'Very gentle clean with hydrocarbon solvent only',
  },
  {
    _id: 'dry-clean-tetrachloroethylene-solvent-only',
    icon: 'app:laundry-icon-dry-clean-tetrachloroethylene-solvent-only',
    path: '/icons/laundry/dry-cleaning/dry-clean-tetrachloroethylene-only.svg',
    group: 'dry cleaning',
    description: 'Dry clean with tetrachloroethylene (PCE) only',
  },
  {
    _id: 'dry-clean-gentle-tetrachloroethylene-only',
    icon: 'app:laundry-icon-dry-clean-gentle-tetrachloroethylene-only',
    path: '/icons/laundry/dry-cleaning/dry-clean-gentle-tetrachloroethylene-only.svg',
    group: 'dry cleaning',
    description: 'Gentle clean with tetrachloroethylene (PCE) only',
  },
  {
    _id: 'dry-clean-very-gentle-tetrachloroethylene-only',
    icon: 'app:laundry-icon-dry-clean-very-gentle-tetrachloroethylene-only',
    path: '/icons/laundry/dry-cleaning/dry-clean-very-gentle-tetrachloroethylene-only.svg',
    group: 'dry cleaning',
    description: 'Very gentle clean with tetrachloroethylene (PCE) only',
  },
  {
    _id: 'wet-cleaning',
    icon: 'app:laundry-icon-wet-cleaning',
    path: '/icons/laundry/wet/wet-cleaning.svg',
    group: 'wet cleaning',
    description: 'Wet clean',
  },
  {
    _id: 'do-not-wet-cleaning',
    icon: 'app:laundry-icon-do-not-wet-cleaning',
    path: '/icons/laundry/wet/do-not-wet-cleaning.svg',
    group: 'wet cleaning',
    description: 'Do not wet clean',
  },
  {
    _id: 'wet-cleaning-gentle',
    icon: 'app:laundry-icon-wet-cleaning-gentle',
    path: '/icons/laundry/wet/wet-cleaning-gentle.svg',
    group: 'wet cleaning',
    description: 'Gentle wet clean',
  },
  {
    _id: 'wet-cleaning-very-gentle',
    icon: 'app:laundry-icon-wet-cleaning-very-gentle',
    path: '/icons/laundry/wet/wet-cleaning-very-gentle.svg',
    group: 'wet cleaning',
    description: 'Very gentle wet clean',
  },
]

export const laundryIconsMap: { [key: string]: laundryIcon } = {}

laundryIcons.forEach((laundryIcon) => (laundryIconsMap[laundryIcon._id] = laundryIcon))
